version: '3.1'
services:
  shifts-app:
    build:
      context: ./../
      dockerfile: docker/app/Dockerfile
    ports:
      - 40000:80
    depends_on:
      - shifts-db
    env_file: .env.app
  shifts-db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env.mysql
  shifts-adminer:
    image: adminer:4.7.7
    ports:
      - 40001:8080
    depends_on:
      - shifts-db